from __future__ import annotations

from backend.agents.sentero.mail.models import MailConfig, MailEncryption


GOOGLE_APP_PASSWORD_HELP_URL = "https://support.google.com/mail/answer/185833"
MICROSOFT_APP_PASSWORD_HELP_URL = "https://support.microsoft.com/account-billing/app-passwords-and-two-step-verification-5896ed9b-4263-e681-128a-a6f2979a7944"
YAHOO_APP_PASSWORD_HELP_URL = "https://help.yahoo.com/kb/generate-manage-third-party-passwords-sln15241.html"
APPLE_APP_PASSWORD_HELP_URL = "https://support.apple.com/102654"


MAIL_PROVIDER_FALLBACKS: dict[str, MailConfig] = {
    "gmx.de": MailConfig(
        imap_host="imap.gmx.com",
        imap_port=993,
        imap_encryption=MailEncryption.SSL,
        smtp_host="mail.gmx.com",
        smtp_port=587,
        smtp_encryption=MailEncryption.STARTTLS,
        auth_method="password-cleartext",
        source="fallback",
    ),
    "web.de": MailConfig(
        imap_host="imap.web.de",
        imap_port=993,
        imap_encryption=MailEncryption.SSL,
        smtp_host="smtp.web.de",
        smtp_port=587,
        smtp_encryption=MailEncryption.STARTTLS,
        auth_method="password-cleartext",
        source="fallback",
    ),
    "t-online.de": MailConfig(
        imap_host="secureimap.t-online.de",
        imap_port=993,
        imap_encryption=MailEncryption.SSL,
        smtp_host="securesmtp.t-online.de",
        smtp_port=465,
        smtp_encryption=MailEncryption.SSL,
        auth_method="password-cleartext",
        source="fallback",
    ),
    "freenet.de": MailConfig(
        imap_host="mx.freenet.de",
        imap_port=993,
        imap_encryption=MailEncryption.SSL,
        smtp_host="mx.freenet.de",
        smtp_port=587,
        smtp_encryption=MailEncryption.STARTTLS,
        auth_method="password-cleartext",
        source="fallback",
    ),
    "1und1.de": MailConfig(
        imap_host="imap.ionos.com",
        imap_port=993,
        imap_encryption=MailEncryption.SSL,
        smtp_host="smtp.ionos.com",
        smtp_port=465,
        smtp_encryption=MailEncryption.SSL,
        auth_method="password-cleartext",
        source="fallback",
    ),
    "strato.de": MailConfig(
        imap_host="imap.strato.de",
        imap_port=993,
        imap_encryption=MailEncryption.SSL,
        smtp_host="smtp.strato.de",
        smtp_port=465,
        smtp_encryption=MailEncryption.SSL,
        auth_method="password-cleartext",
        source="fallback",
    ),
    "gmail.com": MailConfig(
        imap_host="imap.gmail.com",
        imap_port=993,
        imap_encryption=MailEncryption.SSL,
        smtp_host="smtp.gmail.com",
        smtp_port=587,
        smtp_encryption=MailEncryption.STARTTLS,
        auth_method="password-cleartext",
        requires_app_password=True,
        app_password_help_url=GOOGLE_APP_PASSWORD_HELP_URL,
        source="fallback",
    ),
    "outlook.com": MailConfig(
        imap_host="outlook.office365.com",
        imap_port=993,
        imap_encryption=MailEncryption.SSL,
        smtp_host="smtp-mail.outlook.com",
        smtp_port=587,
        smtp_encryption=MailEncryption.STARTTLS,
        auth_method="OAuth2/Modern Auth",
        requires_app_password=True,
        app_password_help_url=MICROSOFT_APP_PASSWORD_HELP_URL,
        source="fallback",
    ),
    "hotmail.com": MailConfig(
        imap_host="outlook.office365.com",
        imap_port=993,
        imap_encryption=MailEncryption.SSL,
        smtp_host="smtp-mail.outlook.com",
        smtp_port=587,
        smtp_encryption=MailEncryption.STARTTLS,
        auth_method="OAuth2/Modern Auth",
        requires_app_password=True,
        app_password_help_url=MICROSOFT_APP_PASSWORD_HELP_URL,
        source="fallback",
    ),
    "yahoo.com": MailConfig(
        imap_host="imap.mail.yahoo.com",
        imap_port=993,
        imap_encryption=MailEncryption.SSL,
        smtp_host="smtp.mail.yahoo.com",
        smtp_port=465,
        smtp_encryption=MailEncryption.SSL,
        auth_method="password-cleartext",
        requires_app_password=True,
        app_password_help_url=YAHOO_APP_PASSWORD_HELP_URL,
        source="fallback",
    ),
    "icloud.com": MailConfig(
        imap_host="imap.mail.me.com",
        imap_port=993,
        imap_encryption=MailEncryption.SSL,
        smtp_host="smtp.mail.me.com",
        smtp_port=587,
        smtp_encryption=MailEncryption.STARTTLS,
        auth_method="password-cleartext",
        requires_app_password=True,
        app_password_help_url=APPLE_APP_PASSWORD_HELP_URL,
        source="fallback",
    ),
}

